import type { Metadata } from "next";
import { League_Spartan } from "next/font/google";
import "./globals.css";
import SideBar from "./components/SideBar";
import Providers from "./providers";

const leagueSpartan = League_Spartan({
  variable: "--font-league-spartan",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${leagueSpartan.variable}  antialiased flex`}>
        <Providers>
          <SideBar />
          <main className="ml-[100px] flex-1">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
